// Schedule data for 2026 - 3 people per shift
export const scheduleData = [
  { date: '03/Jan', dayOfWeek: 6, month: 1, shift: 'afternoon', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '03/Jan', dayOfWeek: 6, month: 1, shift: 'night', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '04/Jan', dayOfWeek: 0, month: 1, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '04/Jan', dayOfWeek: 0, month: 1, shift: 'night', participants: ['Adilson', 'Marcos', 'Mazino'] },
  { date: '07/Jan', dayOfWeek: 3, month: 1, shift: 'night', participants: ['Thiago', 'Vicente', 'Williams'] },
  { date: '10/Jan', dayOfWeek: 6, month: 1, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '11/Jan', dayOfWeek: 0, month: 1, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '11/Jan', dayOfWeek: 0, month: 1, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '14/Jan', dayOfWeek: 3, month: 1, shift: 'night', participants: ['Luiz', 'Marcos', 'Thiago'] },
  { date: '17/Jan', dayOfWeek: 6, month: 1, shift: 'night', participants: ['Vicente', 'Williams', 'Donizete'] },
  { date: '18/Jan', dayOfWeek: 0, month: 1, shift: 'morning', participants: ['Eduardo', 'Elson', 'Flavio'] },
  { date: '18/Jan', dayOfWeek: 0, month: 1, shift: 'night', participants: ['Adilson', 'Henrique', 'Isac'] },
  { date: '21/Jan', dayOfWeek: 3, month: 1, shift: 'night', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '24/Jan', dayOfWeek: 6, month: 1, shift: 'night', participants: ['Marcos', 'Vicente', 'Williams'] },
  { date: '25/Jan', dayOfWeek: 0, month: 1, shift: 'morning', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '25/Jan', dayOfWeek: 0, month: 1, shift: 'night', participants: ['Adilson', 'Flavio', 'Henrique'] },
  { date: '28/Jan', dayOfWeek: 3, month: 1, shift: 'night', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '31/Jan', dayOfWeek: 6, month: 1, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '01/Feb', dayOfWeek: 0, month: 2, shift: 'morning', participants: ['Williams', 'Donizete', 'Eduardo'] },
  { date: '01/Feb', dayOfWeek: 0, month: 2, shift: 'night', participants: ['Mazino', 'Adilson', 'Elson'] },
  { date: '04/Feb', dayOfWeek: 3, month: 2, shift: 'night', participants: ['Thiago', 'Flavio', 'Isac'] },
  { date: '07/Feb', dayOfWeek: 6, month: 2, shift: 'afternoon', participants: ['Henrique', 'Leandro', 'Luís H'] },
  { date: '07/Feb', dayOfWeek: 6, month: 2, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '08/Feb', dayOfWeek: 0, month: 2, shift: 'morning', participants: ['Williams', 'Donizete', 'Eduardo'] },
  { date: '08/Feb', dayOfWeek: 0, month: 2, shift: 'night', participants: ['Adilson', 'Elson', 'Flavio'] },
  { date: '11/Feb', dayOfWeek: 3, month: 2, shift: 'night', participants: ['Thiago', 'Isac', 'Leandro'] },
  { date: '14/Feb', dayOfWeek: 6, month: 2, shift: 'night', participants: ['Henrique', 'Luís H', 'Luiz'] },
  { date: '15/Feb', dayOfWeek: 0, month: 2, shift: 'morning', participants: ['Marcos', 'Vicente', 'Williams'] },
  { date: '15/Feb', dayOfWeek: 0, month: 2, shift: 'night', participants: ['Adilson', 'Donizete', 'Eduardo'] },
  { date: '18/Feb', dayOfWeek: 3, month: 2, shift: 'night', participants: ['Flavio', 'Isac', 'Leandro'] },
  { date: '21/Feb', dayOfWeek: 6, month: 2, shift: 'night', participants: ['Elson', 'Henrique', 'Luís H'] },
  { date: '22/Feb', dayOfWeek: 0, month: 2, shift: 'morning', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '22/Feb', dayOfWeek: 0, month: 2, shift: 'night', participants: ['Adilson', 'Donizete', 'Eduardo'] },
  { date: '25/Feb', dayOfWeek: 3, month: 2, shift: 'night', participants: ['Flavio', 'Isac', 'Leandro'] },
  { date: '28/Feb', dayOfWeek: 6, month: 2, shift: 'night', participants: ['Elson', 'Henrique', 'Luís H'] },
  { date: '01/Mar', dayOfWeek: 0, month: 3, shift: 'morning', participants: ['Williams', 'Luiz', 'Marcos'] },
  { date: '01/Mar', dayOfWeek: 0, month: 3, shift: 'night', participants: ['Mazino', 'Vicente', 'Williams'] },
  { date: '04/Mar', dayOfWeek: 3, month: 3, shift: 'night', participants: ['Thiago', 'Donizete', 'Flavio'] },
  { date: '07/Mar', dayOfWeek: 6, month: 3, shift: 'afternoon', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '07/Mar', dayOfWeek: 6, month: 3, shift: 'night', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '08/Mar', dayOfWeek: 0, month: 3, shift: 'morning', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '08/Mar', dayOfWeek: 0, month: 3, shift: 'night', participants: ['Adilson', 'Williams', 'Donizete'] },
  { date: '11/Mar', dayOfWeek: 3, month: 3, shift: 'night', participants: ['Thiago', 'Flavio', 'Isac'] },
  { date: '14/Mar', dayOfWeek: 6, month: 3, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '15/Mar', dayOfWeek: 0, month: 3, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '15/Mar', dayOfWeek: 0, month: 3, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '18/Mar', dayOfWeek: 3, month: 3, shift: 'night', participants: ['Donizete', 'Flavio', 'Isac'] },
  { date: '21/Mar', dayOfWeek: 6, month: 3, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '22/Mar', dayOfWeek: 0, month: 3, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '22/Mar', dayOfWeek: 0, month: 3, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '25/Mar', dayOfWeek: 3, month: 3, shift: 'night', participants: ['Donizete', 'Flavio', 'Isac'] },
  { date: '28/Mar', dayOfWeek: 6, month: 3, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '29/Mar', dayOfWeek: 0, month: 3, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '29/Mar', dayOfWeek: 0, month: 3, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '01/Apr', dayOfWeek: 3, month: 4, shift: 'night', participants: ['Thiago', 'Williams', 'Donizete'] },
  { date: '04/Apr', dayOfWeek: 6, month: 4, shift: 'afternoon', participants: ['Williams', 'Eduardo', 'Elson'] },
  { date: '04/Apr', dayOfWeek: 6, month: 4, shift: 'night', participants: ['Williams', 'Flavio', 'Henrique'] },
  { date: '05/Apr', dayOfWeek: 0, month: 4, shift: 'morning', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '05/Apr', dayOfWeek: 0, month: 4, shift: 'night', participants: ['Mazino', 'Adilson', 'Luiz'] },
  { date: '08/Apr', dayOfWeek: 3, month: 4, shift: 'night', participants: ['Thiago', 'Marcos', 'Vicente'] },
  { date: '11/Apr', dayOfWeek: 6, month: 4, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '12/Apr', dayOfWeek: 0, month: 4, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '12/Apr', dayOfWeek: 0, month: 4, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '15/Apr', dayOfWeek: 3, month: 4, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '18/Apr', dayOfWeek: 6, month: 4, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '19/Apr', dayOfWeek: 0, month: 4, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '19/Apr', dayOfWeek: 0, month: 4, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '22/Apr', dayOfWeek: 3, month: 4, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '25/Apr', dayOfWeek: 6, month: 4, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '26/Apr', dayOfWeek: 0, month: 4, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '26/Apr', dayOfWeek: 0, month: 4, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '29/Apr', dayOfWeek: 3, month: 4, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '02/May', dayOfWeek: 6, month: 5, shift: 'afternoon', participants: ['Williams', 'Donizete', 'Eduardo'] },
  { date: '02/May', dayOfWeek: 6, month: 5, shift: 'night', participants: ['Williams', 'Elson', 'Flavio'] },
  { date: '03/May', dayOfWeek: 0, month: 5, shift: 'morning', participants: ['Williams', 'Henrique', 'Isac'] },
  { date: '03/May', dayOfWeek: 0, month: 5, shift: 'night', participants: ['Mazino', 'Adilson', 'Leandro'] },
  { date: '06/May', dayOfWeek: 3, month: 5, shift: 'night', participants: ['Thiago', 'Luís H', 'Luiz'] },
  { date: '09/May', dayOfWeek: 6, month: 5, shift: 'night', participants: ['Marcos', 'Vicente', 'Donizete'] },
  { date: '10/May', dayOfWeek: 0, month: 5, shift: 'morning', participants: ['Eduardo', 'Elson', 'Flavio'] },
  { date: '10/May', dayOfWeek: 0, month: 5, shift: 'night', participants: ['Adilson', 'Henrique', 'Isac'] },
  { date: '13/May', dayOfWeek: 3, month: 5, shift: 'night', participants: ['Thiago', 'Leandro', 'Luís H'] },
  { date: '16/May', dayOfWeek: 6, month: 5, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '17/May', dayOfWeek: 0, month: 5, shift: 'morning', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '17/May', dayOfWeek: 0, month: 5, shift: 'night', participants: ['Adilson', 'Flavio', 'Henrique'] },
  { date: '20/May', dayOfWeek: 3, month: 5, shift: 'night', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '23/May', dayOfWeek: 6, month: 5, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '24/May', dayOfWeek: 0, month: 5, shift: 'morning', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '24/May', dayOfWeek: 0, month: 5, shift: 'night', participants: ['Adilson', 'Flavio', 'Henrique'] },
  { date: '27/May', dayOfWeek: 3, month: 5, shift: 'night', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '30/May', dayOfWeek: 6, month: 5, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '31/May', dayOfWeek: 0, month: 5, shift: 'morning', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '31/May', dayOfWeek: 0, month: 5, shift: 'night', participants: ['Adilson', 'Flavio', 'Henrique'] },
  { date: '03/Jun', dayOfWeek: 3, month: 6, shift: 'night', participants: ['Thiago', 'Williams', 'Isac'] },
  { date: '06/Jun', dayOfWeek: 6, month: 6, shift: 'afternoon', participants: ['Williams', 'Leandro', 'Luís H'] },
  { date: '06/Jun', dayOfWeek: 6, month: 6, shift: 'night', participants: ['Williams', 'Luiz', 'Marcos'] },
  { date: '07/Jun', dayOfWeek: 0, month: 6, shift: 'morning', participants: ['Vicente', 'Donizete', 'Eduardo'] },
  { date: '07/Jun', dayOfWeek: 0, month: 6, shift: 'night', participants: ['Mazino', 'Adilson', 'Elson'] },
  { date: '10/Jun', dayOfWeek: 3, month: 6, shift: 'night', participants: ['Thiago', 'Flavio', 'Isac'] },
  { date: '13/Jun', dayOfWeek: 6, month: 6, shift: 'night', participants: ['Henrique', 'Leandro', 'Luís H'] },
  { date: '14/Jun', dayOfWeek: 0, month: 6, shift: 'morning', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '14/Jun', dayOfWeek: 0, month: 6, shift: 'night', participants: ['Adilson', 'Donizete', 'Eduardo'] },
  { date: '17/Jun', dayOfWeek: 3, month: 6, shift: 'night', participants: ['Flavio', 'Isac', 'Leandro'] },
  { date: '20/Jun', dayOfWeek: 6, month: 6, shift: 'night', participants: ['Elson', 'Henrique', 'Luís H'] },
  { date: '21/Jun', dayOfWeek: 0, month: 6, shift: 'morning', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '21/Jun', dayOfWeek: 0, month: 6, shift: 'night', participants: ['Adilson', 'Donizete', 'Eduardo'] },
  { date: '24/Jun', dayOfWeek: 3, month: 6, shift: 'night', participants: ['Flavio', 'Isac', 'Leandro'] },
  { date: '27/Jun', dayOfWeek: 6, month: 6, shift: 'night', participants: ['Elson', 'Henrique', 'Luís H'] },
  { date: '28/Jun', dayOfWeek: 0, month: 6, shift: 'morning', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '28/Jun', dayOfWeek: 0, month: 6, shift: 'night', participants: ['Adilson', 'Donizete', 'Eduardo'] },
  { date: '01/Jul', dayOfWeek: 3, month: 7, shift: 'night', participants: ['Thiago', 'Williams', 'Flavio'] },
  { date: '04/Jul', dayOfWeek: 6, month: 7, shift: 'afternoon', participants: ['Williams', 'Elson', 'Henrique'] },
  { date: '04/Jul', dayOfWeek: 6, month: 7, shift: 'night', participants: ['Williams', 'Isac', 'Leandro'] },
  { date: '05/Jul', dayOfWeek: 0, month: 7, shift: 'morning', participants: ['Luís H', 'Luiz', 'Marcos'] },
  { date: '05/Jul', dayOfWeek: 0, month: 7, shift: 'night', participants: ['Mazino', 'Vicente', 'Adilson'] },
  { date: '08/Jul', dayOfWeek: 3, month: 7, shift: 'night', participants: ['Thiago', 'Donizete', 'Flavio'] },
  { date: '11/Jul', dayOfWeek: 6, month: 7, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '12/Jul', dayOfWeek: 0, month: 7, shift: 'morning', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '12/Jul', dayOfWeek: 0, month: 7, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '15/Jul', dayOfWeek: 3, month: 7, shift: 'night', participants: ['Donizete', 'Flavio', 'Isac'] },
  { date: '18/Jul', dayOfWeek: 6, month: 7, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '19/Jul', dayOfWeek: 0, month: 7, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '19/Jul', dayOfWeek: 0, month: 7, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '22/Jul', dayOfWeek: 3, month: 7, shift: 'night', participants: ['Donizete', 'Flavio', 'Isac'] },
  { date: '25/Jul', dayOfWeek: 6, month: 7, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '26/Jul', dayOfWeek: 0, month: 7, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '26/Jul', dayOfWeek: 0, month: 7, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '29/Jul', dayOfWeek: 3, month: 7, shift: 'night', participants: ['Donizete', 'Flavio', 'Isac'] },
  { date: '01/Aug', dayOfWeek: 6, month: 8, shift: 'afternoon', participants: ['Williams', 'Eduardo', 'Elson'] },
  { date: '01/Aug', dayOfWeek: 6, month: 8, shift: 'night', participants: ['Williams', 'Henrique', 'Leandro'] },
  { date: '02/Aug', dayOfWeek: 0, month: 8, shift: 'morning', participants: ['Williams', 'Luís H', 'Luiz'] },
  { date: '02/Aug', dayOfWeek: 0, month: 8, shift: 'night', participants: ['Mazino', 'Adilson', 'Marcos'] },
  { date: '05/Aug', dayOfWeek: 3, month: 8, shift: 'night', participants: ['Thiago', 'Vicente', 'Donizete'] },
  { date: '08/Aug', dayOfWeek: 6, month: 8, shift: 'night', participants: ['Eduardo', 'Elson', 'Flavio'] },
  { date: '09/Aug', dayOfWeek: 0, month: 8, shift: 'morning', participants: ['Henrique', 'Isac', 'Leandro'] },
  { date: '09/Aug', dayOfWeek: 0, month: 8, shift: 'night', participants: ['Adilson', 'Luís H', 'Luiz'] },
  { date: '12/Aug', dayOfWeek: 3, month: 8, shift: 'night', participants: ['Thiago', 'Marcos', 'Vicente'] },
  { date: '15/Aug', dayOfWeek: 6, month: 8, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '16/Aug', dayOfWeek: 0, month: 8, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '16/Aug', dayOfWeek: 0, month: 8, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '19/Aug', dayOfWeek: 3, month: 8, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '22/Aug', dayOfWeek: 6, month: 8, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '23/Aug', dayOfWeek: 0, month: 8, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '23/Aug', dayOfWeek: 0, month: 8, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '26/Aug', dayOfWeek: 3, month: 8, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '29/Aug', dayOfWeek: 6, month: 8, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '30/Aug', dayOfWeek: 0, month: 8, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '30/Aug', dayOfWeek: 0, month: 8, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '02/Sep', dayOfWeek: 3, month: 9, shift: 'night', participants: ['Thiago', 'Williams', 'Luiz'] },
  { date: '05/Sep', dayOfWeek: 6, month: 9, shift: 'afternoon', participants: ['Williams', 'Marcos', 'Vicente'] },
  { date: '05/Sep', dayOfWeek: 6, month: 9, shift: 'night', participants: ['Williams', 'Donizete', 'Eduardo'] },
  { date: '06/Sep', dayOfWeek: 0, month: 9, shift: 'morning', participants: ['Elson', 'Flavio', 'Henrique'] },
  { date: '06/Sep', dayOfWeek: 0, month: 9, shift: 'night', participants: ['Mazino', 'Adilson', 'Isac'] },
  { date: '09/Sep', dayOfWeek: 3, month: 9, shift: 'night', participants: ['Thiago', 'Leandro', 'Luís H'] },
  { date: '12/Sep', dayOfWeek: 6, month: 9, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '13/Sep', dayOfWeek: 0, month: 9, shift: 'morning', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '13/Sep', dayOfWeek: 0, month: 9, shift: 'night', participants: ['Adilson', 'Flavio', 'Henrique'] },
  { date: '16/Sep', dayOfWeek: 3, month: 9, shift: 'night', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '19/Sep', dayOfWeek: 6, month: 9, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '20/Sep', dayOfWeek: 0, month: 9, shift: 'morning', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '20/Sep', dayOfWeek: 0, month: 9, shift: 'night', participants: ['Adilson', 'Flavio', 'Henrique'] },
  { date: '23/Sep', dayOfWeek: 3, month: 9, shift: 'night', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '26/Sep', dayOfWeek: 6, month: 9, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '27/Sep', dayOfWeek: 0, month: 9, shift: 'morning', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '27/Sep', dayOfWeek: 0, month: 9, shift: 'night', participants: ['Adilson', 'Flavio', 'Henrique'] },
  { date: '30/Sep', dayOfWeek: 3, month: 9, shift: 'night', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '03/Oct', dayOfWeek: 6, month: 10, shift: 'afternoon', participants: ['Williams', 'Luiz', 'Marcos'] },
  { date: '03/Oct', dayOfWeek: 6, month: 10, shift: 'night', participants: ['Williams', 'Vicente', 'Donizete'] },
  { date: '04/Oct', dayOfWeek: 0, month: 10, shift: 'morning', participants: ['Williams', 'Eduardo', 'Elson'] },
  { date: '04/Oct', dayOfWeek: 0, month: 10, shift: 'night', participants: ['Mazino', 'Adilson', 'Flavio'] },
  { date: '07/Oct', dayOfWeek: 3, month: 10, shift: 'night', participants: ['Thiago', 'Isac', 'Leandro'] },
  { date: '10/Oct', dayOfWeek: 6, month: 10, shift: 'night', participants: ['Henrique', 'Luís H', 'Luiz'] },
  { date: '11/Oct', dayOfWeek: 0, month: 10, shift: 'morning', participants: ['Marcos', 'Vicente', 'Donizete'] },
  { date: '11/Oct', dayOfWeek: 0, month: 10, shift: 'night', participants: ['Adilson', 'Eduardo', 'Elson'] },
  { date: '14/Oct', dayOfWeek: 3, month: 10, shift: 'night', participants: ['Thiago', 'Flavio', 'Isac'] },
  { date: '17/Oct', dayOfWeek: 6, month: 10, shift: 'night', participants: ['Henrique', 'Leandro', 'Luís H'] },
  { date: '18/Oct', dayOfWeek: 0, month: 10, shift: 'morning', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '18/Oct', dayOfWeek: 0, month: 10, shift: 'night', participants: ['Adilson', 'Donizete', 'Eduardo'] },
  { date: '21/Oct', dayOfWeek: 3, month: 10, shift: 'night', participants: ['Flavio', 'Isac', 'Leandro'] },
  { date: '24/Oct', dayOfWeek: 6, month: 10, shift: 'night', participants: ['Elson', 'Henrique', 'Luís H'] },
  { date: '25/Oct', dayOfWeek: 0, month: 10, shift: 'morning', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '25/Oct', dayOfWeek: 0, month: 10, shift: 'night', participants: ['Adilson', 'Donizete', 'Eduardo'] },
  { date: '28/Oct', dayOfWeek: 3, month: 10, shift: 'night', participants: ['Flavio', 'Isac', 'Leandro'] },
  { date: '31/Oct', dayOfWeek: 6, month: 10, shift: 'night', participants: ['Elson', 'Henrique', 'Luís H'] },
  { date: '01/Nov', dayOfWeek: 0, month: 11, shift: 'morning', participants: ['Williams', 'Luiz', 'Marcos'] },
  { date: '01/Nov', dayOfWeek: 0, month: 11, shift: 'night', participants: ['Mazino', 'Williams', 'Vicente'] },
  { date: '04/Nov', dayOfWeek: 3, month: 11, shift: 'night', participants: ['Thiago', 'Williams', 'Donizete'] },
  { date: '07/Nov', dayOfWeek: 6, month: 11, shift: 'afternoon', participants: ['Eduardo', 'Elson', 'Flavio'] },
  { date: '07/Nov', dayOfWeek: 6, month: 11, shift: 'night', participants: ['Henrique', 'Isac', 'Leandro'] },
  { date: '08/Nov', dayOfWeek: 0, month: 11, shift: 'morning', participants: ['Luís H', 'Luiz', 'Marcos'] },
  { date: '08/Nov', dayOfWeek: 0, month: 11, shift: 'night', participants: ['Adilson', 'Vicente', 'Donizete'] },
  { date: '11/Nov', dayOfWeek: 3, month: 11, shift: 'night', participants: ['Thiago', 'Flavio', 'Isac'] },
  { date: '14/Nov', dayOfWeek: 6, month: 11, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '15/Nov', dayOfWeek: 0, month: 11, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '15/Nov', dayOfWeek: 0, month: 11, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '18/Nov', dayOfWeek: 3, month: 11, shift: 'night', participants: ['Donizete', 'Flavio', 'Isac'] },
  { date: '21/Nov', dayOfWeek: 6, month: 11, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '22/Nov', dayOfWeek: 0, month: 11, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '22/Nov', dayOfWeek: 0, month: 11, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '25/Nov', dayOfWeek: 3, month: 11, shift: 'night', participants: ['Donizete', 'Flavio', 'Isac'] },
  { date: '28/Nov', dayOfWeek: 6, month: 11, shift: 'night', participants: ['Eduardo', 'Elson', 'Henrique'] },
  { date: '29/Nov', dayOfWeek: 0, month: 11, shift: 'morning', participants: ['Leandro', 'Luís H', 'Luiz'] },
  { date: '29/Nov', dayOfWeek: 0, month: 11, shift: 'night', participants: ['Adilson', 'Marcos', 'Vicente'] },
  { date: '02/Dec', dayOfWeek: 3, month: 12, shift: 'night', participants: ['Thiago', 'Williams', 'Donizete'] },
  { date: '05/Dec', dayOfWeek: 6, month: 12, shift: 'afternoon', participants: ['Williams', 'Eduardo', 'Elson'] },
  { date: '05/Dec', dayOfWeek: 6, month: 12, shift: 'night', participants: ['Williams', 'Flavio', 'Henrique'] },
  { date: '06/Dec', dayOfWeek: 0, month: 12, shift: 'morning', participants: ['Isac', 'Leandro', 'Luís H'] },
  { date: '06/Dec', dayOfWeek: 0, month: 12, shift: 'night', participants: ['Mazino', 'Adilson', 'Luiz'] },
  { date: '09/Dec', dayOfWeek: 3, month: 12, shift: 'night', participants: ['Thiago', 'Marcos', 'Vicente'] },
  { date: '12/Dec', dayOfWeek: 6, month: 12, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '13/Dec', dayOfWeek: 0, month: 12, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '13/Dec', dayOfWeek: 0, month: 12, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '16/Dec', dayOfWeek: 3, month: 12, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '19/Dec', dayOfWeek: 6, month: 12, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '20/Dec', dayOfWeek: 0, month: 12, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '20/Dec', dayOfWeek: 0, month: 12, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '23/Dec', dayOfWeek: 3, month: 12, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
  { date: '26/Dec', dayOfWeek: 6, month: 12, shift: 'night', participants: ['Donizete', 'Eduardo', 'Elson'] },
  { date: '27/Dec', dayOfWeek: 0, month: 12, shift: 'morning', participants: ['Flavio', 'Henrique', 'Isac'] },
  { date: '27/Dec', dayOfWeek: 0, month: 12, shift: 'night', participants: ['Adilson', 'Leandro', 'Luís H'] },
  { date: '30/Dec', dayOfWeek: 3, month: 12, shift: 'night', participants: ['Luiz', 'Marcos', 'Vicente'] },
];
